//Crear evento con detalles

POST http://localhost:4000/eventodetalles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiRmVkZTkxMSIsImlkIjoxLCJpYXQiOjE2MjgwOTE4OTB9.1f18jex7CqDeCqbCRfohaSA6CPIGKRgazzxp0hsnBUs

 { 
    "titulo":"Fiesta del Asado con Cuero",
    "descripcion":"Recorra los stands desgustando el mejor asado con cuero de la región.",
    "destacado":true,
    "imagenUrl":"www.tecomoconcueroytodo.com", 
    "localidad":"Parana, Entre Rios",
    "detalles":[
        {
            "fecha":"25/08/2021",
            "hora":"12:00",
            "precio":2000
        }
    ]
}